CREATE ROLE webadmin NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN NOREPLICATION NOBYPASSRLS PASSWORD '12345';
GRANT SELECT ON TABLE public.category TO webadmin;
GRANT UPDATE, SELECT, INSERT ON TABLE public.game TO webadmin;
GRANT UPDATE, SELECT, INSERT ON TABLE public.game_spy TO webadmin;
GRANT UPDATE, SELECT, INSERT, DELETE ON TABLE public."location" TO webadmin;
GRANT UPDATE, SELECT, INSERT, DELETE ON TABLE public.location_join TO webadmin;
GRANT UPDATE, SELECT, INSERT, DELETE ON TABLE public.player TO webadmin;
GRANT UPDATE, SELECT, INSERT, DELETE ON TABLE public.player_join TO webadmin;
GRANT ALL ON SEQUENCE public.category_category_id_seq TO webadmin;
GRANT ALL ON SEQUENCE public.game_game_id_seq TO webadmin;
GRANT ALL ON SEQUENCE public.game_spy_game_spy_id_seq TO webadmin;
GRANT ALL ON SEQUENCE public.location_join_location_join_id_seq TO webadmin;
GRANT ALL ON SEQUENCE public.location_location_id_seq TO webadmin;
GRANT ALL ON SEQUENCE public.player_join_player_join_id_seq TO webadmin;
GRANT ALL ON SEQUENCE public.player_player_id_seq TO webadmin;
