CREATE ROLE webadmin NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN NOREPLICATION NOBYPASSRLS PASSWORD '12345';
GRANT SELECT ON TABLE public.category TO webadmin;
GRANT UPDATE, SELECT, INSERT ON TABLE public.game TO webadmin;
GRANT UPDATE, SELECT, INSERT ON TABLE public.game_spy TO webadmin;
GRANT UPDATE, SELECT, INSERT, DELETE ON TABLE public."location" TO webadmin;
GRANT UPDATE, SELECT, INSERT, DELETE ON TABLE public.location_join TO webadmin;
GRANT UPDATE, SELECT, INSERT, DELETE ON TABLE public.player TO webadmin;
