insert into category (name,type) values ('Custom', 'locationlist');
insert into category (name,type) values ('Spyfall 1', 'locationlist');
insert into category (name,type) values ('Spyfall 2','locationlist');

insert into location (name, category_id) values ('Airplane',2);
insert into location (name, category_id) values ('Bank',2);
insert into location (name, category_id) values ('Beach',2);
insert into location (name, category_id) values ('Broadway Theater',2);
insert into location (name, category_id) values ('Casino',2);
insert into location (name, category_id) values ('Cathedral',2);
insert into location (name, category_id) values ('Circus Tent',2);
insert into location (name, category_id) values ('Corporate Party',2);
insert into location (name, category_id) values ('Crusader Army',2);
insert into location (name, category_id) values ('Day Spa',2);
insert into location (name, category_id) values ('Embassy',2);
insert into location (name, category_id) values ('Hospital',2);
insert into location (name, category_id) values ('Hotel',2);
insert into location (name, category_id) values ('Military Base',2);
insert into location (name, category_id) values ('Movie Studio',2);
insert into location (name, category_id) values ('Ocean Liner',2);
insert into location (name, category_id) values ('Passenger Train',2);
insert into location (name, category_id) values ('Pirate Ship',2);
insert into location (name, category_id) values ('Polar Station',2);
insert into location (name, category_id) values ('Police Station',2);
insert into location (name, category_id) values ('Restaurant',2);
insert into location (name, category_id) values ('School',2);
insert into location (name, category_id) values ('Gas Station',2);
insert into location (name, category_id) values ('Space Station',2);
insert into location (name, category_id) values ('Submarine',2);
insert into location (name, category_id) values ('Supermarket',2);
insert into location (name, category_id) values ('University',2);

insert into location (name, category_id) values ('Amusement Park',3);
insert into location (name, category_id) values ('Art Museum',3);
insert into location (name, category_id) values ('Candy Factory',3);
insert into location (name, category_id) values ('Cat Show',3);
insert into location (name, category_id) values ('Cemetary',3);
insert into location (name, category_id) values ('Coal Mine',3);
insert into location (name, category_id) values ('Construction Site',3);
insert into location (name, category_id) values ('Gaming Convention',3);
insert into location (name, category_id) values ('Harbor Docks',3);
insert into location (name, category_id) values ('Stadium',3);
insert into location (name, category_id) values ('Jail',3);
insert into location (name, category_id) values ('Jazz Club',3);
insert into location (name, category_id) values ('Library',3);
insert into location (name, category_id) values ('Night Club',3);
insert into location (name, category_id) values ('Race Track',3);
insert into location (name, category_id) values ('Retirement Home',3);
insert into location (name, category_id) values ('Rock Concert',3);
insert into location (name, category_id) values ('Sightseeing Bus',3);
insert into location (name, category_id) values ('Subway',3);
insert into location (name, category_id) values ('The U.N.',3);
insert into location (name, category_id) values ('Vineyard',3);
insert into location (name, category_id) values ('Wedding',3);
insert into location (name, category_id) values ('Zoo',3);